# Generated by Django 3.1.3 on 2021-04-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImgCaptcha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captcha_text', models.CharField(max_length=255, unique=True)),
                ('url_image', models.CharField(max_length=255, unique=True)),
                ('style_captcha', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
