# Generated by Django 3.1.3 on 2021-04-03 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captcha_web_services', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImgCaptcha',
        ),
    ]
